services:
  typesense:
    image: typesense/typesense:27.0
    restart: unless-stopped
    volumes:
      - ./typesense/data:/data
    command: "--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors"
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    ports:
      - "8108:8108" # To setup and debug Typesense
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./server/server.conf.template:/etc/nginx/templates/server.conf.template:ro
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src:/usr/share/nginx/html
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    depends_on:
      - typesense
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  typesense-data:
